# Form implementation generated from reading ui file 'Diem.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc
from openpyxl import Workbook
import os

connection_string = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=PHONG-VU\\SQLEXPRESS;'
    'DATABASE=QuanLySinhVien;'
    'UID=sa;'
    'PWD=223003'
    )

class Ui_DiemWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 447)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtMaMon = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaMon.setGeometry(QtCore.QRect(100, 50, 113, 21))
        self.txtMaMon.setObjectName("txtMaMon")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(30, 330, 93, 28))
        self.btnAdd.setObjectName("btnAdd")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(390, 100, 93, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.txtDiem = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtDiem.setGeometry(QtCore.QRect(370, 10, 113, 21))
        self.txtDiem.setObjectName("txtDiem")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(380, 330, 93, 28))
        self.btnDelete.setObjectName("btnDelete")
        self.txtTK = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTK.setGeometry(QtCore.QRect(220, 100, 161, 31))
        self.txtTK.setObjectName("txtTK")
        self.tb_SinhVien = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tb_SinhVien.setGeometry(QtCore.QRect(10, 150, 461, 171))
        self.tb_SinhVien.setObjectName("tb_SinhVien")
        self.tb_SinhVien.setColumnCount(3)
        self.tb_SinhVien.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnUpdate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(210, 330, 93, 28))
        self.btnUpdate.setObjectName("btnUpdate")
        self.txtMaSV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaSV.setGeometry(QtCore.QRect(100, 10, 113, 21))
        self.txtMaSV.setObjectName("txtMaSV")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnThongKe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThongKe.setGeometry(QtCore.QRect(10, 110, 93, 28))
        self.btnThongKe.setObjectName("btnThongKe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.load_data()
        self.tb_SinhVien.cellClicked.connect(self.populate_fields)
        self.btnAdd.clicked.connect(self.add_data)
        self.btnUpdate.clicked.connect(self.update_data)
        self.btnDelete.clicked.connect(self.delete_data)
        self.btnSearch.clicked.connect(self.search_data)
        self.btnThongKe.clicked.connect(self.btnThongKe_clicked)  # Kết nối nút Thống kê

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAdd.setText(_translate("MainWindow", "Thêm"))
        self.btnSearch.setText(_translate("MainWindow", "Tìm Kiếm"))
        self.label_2.setText(_translate("MainWindow", "Mã môn"))
        self.btnDelete.setText(_translate("MainWindow", "Xóa"))
        item = self.tb_SinhVien.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã SV"))
        item = self.tb_SinhVien.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mã Môn"))
        item = self.tb_SinhVien.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Điểm"))
        self.label.setText(_translate("MainWindow", "Mã SV"))
        self.btnUpdate.setText(_translate("MainWindow", "Sửa"))
        self.label_3.setText(_translate("MainWindow", "Điểm"))
        self.btnThongKe.setText(_translate("MainWindow", "Thống kê"))

    def load_data(self):
        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM Diem")
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_num, row_data in enumerate(rows):
                for col_num, data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_num, col_num, QtWidgets.QTableWidgetItem(str(data)))

            conn.close()

        except pyodbc.Error as e:
            print("Lỗi kết nối", e)
    
    def add_data(self):
        ma_sv = self.txtMaSV.text()
        ma_mon = self.txtMaMon.text()
        diem = self.txtDiem.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO Diem (MaSV, MaMon, Diem) VALUES (?, ?, ?)",
                (ma_sv, ma_mon, diem)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def update_data(self):
        ma_sv = self.txtMaSV.text()
        ma_mon = self.txtMaMon.text()
        diem = self.txtDiem.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE Diem SET MaMon = ?, Diem = ? WHERE MaSV = ?",
                (ma_mon,diem, ma_sv)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def delete_data(self):
        ma_sv = self.txtMaSV.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("DELETE FROM Diem WHERE MaSV = ?", (ma_sv,))
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def search_data(self):
        search_term = self.txtTK.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            query = "SELECT MaSV, MaMon,Diem FROM Diem WHERE MaSV LIKE ? OR MaMon LIKE ?"
            cursor.execute(query, ('%' + search_term + '%', '%' + search_term + '%'))
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_idx, row_data in enumerate(rows):
                for col_idx, col_data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_idx, col_idx, QtWidgets.QTableWidgetItem(str(col_data)))

            conn.close()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def populate_fields(self, row, column):
        self.txtMaSV.setText(self.tb_SinhVien.item(row, 0).text())
        self.txtMaMon.setText(self.tb_SinhVien.item(row, 1).text())
        self.txtDiem.setText(self.tb_SinhVien.item(row, 2).text())

    def btnThongKe_clicked(self):
        wb = Workbook()
        ws = wb.active
        ws.title = "Danh sách điểm"

        # Ghi tiêu đề cột
        columns = ["Mã SV", "Mã Môn", "Điểm"]
        for col_idx, col_name in enumerate(columns, 1):
            ws.cell(row=1, column=col_idx, value=col_name)

        # Ghi dữ liệu từ table widget vào worksheet
        for row_idx in range(self.tb_SinhVien.rowCount()):
            for col_idx in range(self.tb_SinhVien.columnCount()):
                item = self.tb_SinhVien.item(row_idx, col_idx)
                ws.cell(row=row_idx + 2, column=col_idx + 1, value=item.text())

        # Đường dẫn lưu file
        directory = "E:\Python"
        if not os.path.exists(directory):
            os.makedirs(directory)
        file_path = os.path.join(directory, "DanhSachDiem.xlsx")
        
        # Lưu workbook thành file Excel
        wb.save(file_path)
        QtWidgets.QMessageBox.information(None, "Thông báo", f"File đã được lưu tại {file_path}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_DiemWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
