# Form implementation generated from reading ui file 'LopHoc.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc
connection_string = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=PHONG-VU\\SQLEXPRESS;'
    'DATABASE=QuanLySinhVien;'
    'UID=sa;'
    'PWD=223003'
)

class Ui_LopHocWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 499)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtTK = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTK.setGeometry(QtCore.QRect(300, 160, 161, 31))
        self.txtTK.setObjectName("txtTK")
        self.txtKhoa = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtKhoa.setGeometry(QtCore.QRect(400, 100, 113, 21))
        self.txtKhoa.setObjectName("txtKhoa")
        self.txtTenLop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTenLop.setGeometry(QtCore.QRect(400, 60, 113, 21))
        self.txtTenLop.setObjectName("txtTenLop")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(80, 380, 93, 28))
        self.btnAdd.setObjectName("btnAdd")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(470, 160, 93, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtMaLop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaLop.setGeometry(QtCore.QRect(140, 60, 113, 21))
        self.txtMaLop.setObjectName("txtMaLop")
        self.txtMaSV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaSV.setGeometry(QtCore.QRect(140, 100, 113, 21))
        self.txtMaSV.setObjectName("txtMaSV")
        self.btnUpdate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(210, 380, 93, 28))
        self.btnUpdate.setObjectName("btnUpdate")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tb_SinhVien = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tb_SinhVien.setGeometry(QtCore.QRect(50, 200, 511, 171))
        self.tb_SinhVien.setObjectName("tb_SinhVien")
        self.tb_SinhVien.setColumnCount(4)
        self.tb_SinhVien.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(3, item)
        self.btnDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(340, 380, 93, 28))
        self.btnDelete.setObjectName("btnDelete")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.load_data()
        self.tb_SinhVien.cellClicked.connect(self.populate_fields)

        # Connect buttons to their respective methods
        self.btnAdd.clicked.connect(self.add_data)
        self.btnUpdate.clicked.connect(self.update_data)
        self.btnDelete.clicked.connect(self.delete_data)
        self.btnSearch.clicked.connect(self.search_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAdd.setText(_translate("MainWindow", "Thêm"))
        self.btnSearch.setText(_translate("MainWindow", "Tìm Kiếm"))
        self.label_2.setText(_translate("MainWindow", "Mã SV"))
        self.btnUpdate.setText(_translate("MainWindow", "Sửa"))
        self.label_4.setText(_translate("MainWindow", "Khoa"))
        self.label_3.setText(_translate("MainWindow", "Tên lớp"))
        item = self.tb_SinhVien.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Lớp"))
        item = self.tb_SinhVien.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mã SV"))
        item = self.tb_SinhVien.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tên Lớp"))
        item = self.tb_SinhVien.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Khoa"))
        self.btnDelete.setText(_translate("MainWindow", "Xóa"))
        self.label.setText(_translate("MainWindow", "Mã lớp"))

    def load_data(self):
        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM LopHoc")
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_num, row_data in enumerate(rows):
                for col_num, data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_num, col_num, QtWidgets.QTableWidgetItem(str(data)))

            conn.close()

        except pyodbc.Error as e:
            print("Lỗi kết nối", e)

    def populate_fields(self, row, column):
        self.txtMaLop.setText(self.tb_SinhVien.item(row, 0).text())
        self.txtMaSV.setText(self.tb_SinhVien.item(row, 1).text())
        self.txtTenLop.setText(self.tb_SinhVien.item(row, 2).text())
        self.txtKhoa.setText(self.tb_SinhVien.item(row, 3).text())
    
    def add_data(self):
        ma_lop = self.txtMaLop.text()
        ma_sv = self.txtMaSV.text()
        ten_lop = self.txtTenLop.text()
        khoa = self.txtKhoa.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO LopHoc (MaLop, MaSV, TenLop, Khoa) VALUES (?, ?, ?, ?)",
                (ma_lop, ma_sv, ten_lop, khoa)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def update_data(self):
        ma_lop = self.txtMaLop.text()
        ma_sv = self.txtMaSV.text()
        ten_lop = self.txtTenLop.text()
        khoa = self.txtKhoa.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE LopHoc SET MaSV = ?, TenLop = ?, Khoa = ? WHERE MaLop = ?",
                ( ma_sv, ten_lop, khoa, ma_lop)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def delete_data(self):
        ma_lop = self.txtMaLop.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("DELETE FROM LopHoc WHERE MaLop = ?", (ma_lop,))
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def search_data(self):
        search_term = self.txtTK.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            query = "SELECT MaLop, MaSV, TenLop, Khoa FROM LopHoc WHERE MaLop LIKE ? OR MaSV LIKE ?"
            cursor.execute(query, ('%' + search_term + '%', '%' + search_term + '%'))
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_idx, row_data in enumerate(rows):
                for col_idx, col_data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_idx, col_idx, QtWidgets.QTableWidgetItem(str(col_data)))

            conn.close()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LopHocWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
