# Form implementation generated from reading ui file 'MonHoc.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc

connection_string = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=PHONG-VU\\SQLEXPRESS;'
    'DATABASE=QuanLySinhVien;'
    'UID=sa;'
    'PWD=223003'
    )
class Ui_MonHocWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 486)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(420, 130, 93, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.btnDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(410, 360, 93, 28))
        self.btnDelete.setObjectName("btnDelete")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(60, 360, 93, 28))
        self.btnAdd.setObjectName("btnAdd")
        self.txtTenMon = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTenMon.setGeometry(QtCore.QRect(130, 80, 113, 21))
        self.txtTenMon.setObjectName("txtTenMon")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtMaMon = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaMon.setGeometry(QtCore.QRect(130, 40, 113, 21))
        self.txtMaMon.setObjectName("txtMaMon")
        self.txtTK = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTK.setGeometry(QtCore.QRect(250, 130, 161, 31))
        self.txtTK.setObjectName("txtTK")
        self.txtSoTC = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSoTC.setGeometry(QtCore.QRect(400, 40, 113, 21))
        self.txtSoTC.setObjectName("txtSoTC")
        self.btnUpdate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(240, 360, 93, 28))
        self.btnUpdate.setObjectName("btnUpdate")
        self.tb_SinhVien = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tb_SinhVien.setGeometry(QtCore.QRect(40, 180, 471, 171))
        self.tb_SinhVien.setObjectName("tb_SinhVien")
        self.tb_SinhVien.setColumnCount(3)
        self.tb_SinhVien.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(2, item)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 40, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.load_data()
        self.tb_SinhVien.cellClicked.connect(self.populate_fields)
        self.btnAdd.clicked.connect(self.add_data)
        self.btnUpdate.clicked.connect(self.update_data)
        self.btnDelete.clicked.connect(self.delete_data)
        self.btnSearch.clicked.connect(self.search_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Tên môn"))
        self.btnSearch.setText(_translate("MainWindow", "Tìm Kiếm"))
        self.btnDelete.setText(_translate("MainWindow", "Xóa"))
        self.btnAdd.setText(_translate("MainWindow", "Thêm"))
        self.label.setText(_translate("MainWindow", "Mã môn"))
        self.btnUpdate.setText(_translate("MainWindow", "Sửa"))
        item = self.tb_SinhVien.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Môn"))
        item = self.tb_SinhVien.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên Môn"))
        item = self.tb_SinhVien.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Số Tín Chỉ"))
        self.label_3.setText(_translate("MainWindow", "Số tín chỉ"))

    def load_data(self):
        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM MonHoc")
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_num, row_data in enumerate(rows):
                for col_num, data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_num, col_num, QtWidgets.QTableWidgetItem(str(data)))

            conn.close()

        except pyodbc.Error as e:
            print("Lỗi kết nối", e)
    def populate_fields(self, row, column):
        self.txtMaMon.setText(self.tb_SinhVien.item(row, 0).text())
        self.txtTenMon.setText(self.tb_SinhVien.item(row, 1).text())
        self.txtSoTC.setText(self.tb_SinhVien.item(row, 2).text())

    def add_data(self):
        ma_mon = self.txtMaMon.text()
        Ten_Mon = self.txtTenMon.text()
        so_TC = self.txtSoTC.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO MonHoc (MaMon, TenMon, SoTinChi) VALUES (?, ?, ?)",
                (ma_mon, Ten_Mon, so_TC)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def update_data(self):
        ma_mon = self.txtMaMon.text()
        Ten_Mon = self.txtTenMon.text()
        so_TC = self.txtSoTC.text()
        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE MonHoc SET TenMon = ?, SoTinChi = ? WHERE MaMon = ?",
                (Ten_Mon, so_TC, ma_mon)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def delete_data(self):
        ma_mon = self.txtMaMon.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("DELETE FROM MonHoc WHERE MaMon = ?", (ma_mon,))
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def search_data(self):
        search_term = self.txtTK.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            query = "SELECT MaMon, TenMon, SoTinChi FROM MaMon WHERE MaMon LIKE ? OR TenMon LIKE ?"
            cursor.execute(query, ('%' + search_term + '%', '%' + search_term + '%'))
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_idx, row_data in enumerate(rows):
                for col_idx, col_data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_idx, col_idx, QtWidgets.QTableWidgetItem(str(col_data)))

            conn.close()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MonHocWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
