# Form implementation generated from reading ui file 'sinhvien.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc
from openpyxl import Workbook
import os

connection_string = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=PHONG-VU\\SQLEXPRESS;'
    'DATABASE=QuanLySinhVien;'
    'UID=sa;'
    'PWD=223003'
)

class Ui_sinhvienWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 405)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtMaSV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaSV.setGeometry(QtCore.QRect(90, 20, 113, 21))
        self.txtMaSV.setObjectName("txtMaSV")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtHoTen = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtHoTen.setGeometry(QtCore.QRect(90, 60, 113, 21))
        self.txtHoTen.setObjectName("txtHoTen")
        self.txtNgaySinh = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNgaySinh.setGeometry(QtCore.QRect(90, 100, 113, 21))
        self.txtNgaySinh.setObjectName("txtNgaySinh")
        self.txtGT = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGT.setGeometry(QtCore.QRect(360, 20, 113, 21))
        self.txtGT.setObjectName("txtGT")
        self.txtDiaChi = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtDiaChi.setGeometry(QtCore.QRect(360, 60, 113, 21))
        self.txtDiaChi.setObjectName("txtDiaChi")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 60, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtTK = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTK.setGeometry(QtCore.QRect(430, 110, 161, 31))
        self.txtTK.setObjectName("txtTK")
        self.tb_SinhVien = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tb_SinhVien.setGeometry(QtCore.QRect(0, 160, 711, 171))
        self.tb_SinhVien.setObjectName("tb_SinhVien")
        self.tb_SinhVien.setColumnCount(5)
        self.tb_SinhVien.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_SinhVien.setHorizontalHeaderItem(4, item)
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(40, 340, 93, 28))
        self.btnAdd.setObjectName("btnAdd")
        self.btnUpdate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(210, 340, 93, 28))
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(370, 340, 93, 28))
        self.btnDelete.setObjectName("btnDelete")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(600, 110, 93, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.btnThongKe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThongKe.setGeometry(QtCore.QRect(540, 340, 93, 28))
        self.btnThongKe.setObjectName("btnThongKe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.load_data()
        self.tb_SinhVien.cellClicked.connect(self.populate_fields)
        self.btnAdd.clicked.connect(self.add_data)
        self.btnUpdate.clicked.connect(self.update_data)
        self.btnDelete.clicked.connect(self.delete_data)
        self.btnSearch.clicked.connect(self.search_data)
        self.btnThongKe.clicked.connect(self.btnThongKe_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Mã SV"))
        self.label_2.setText(_translate("MainWindow", "Họ tên"))
        self.label_3.setText(_translate("MainWindow", "Ngày sinh"))
        self.label_4.setText(_translate("MainWindow", "Giới tính"))
        self.label_5.setText(_translate("MainWindow", "Địa chỉ"))
        item = self.tb_SinhVien.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã SV"))
        item = self.tb_SinhVien.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Họ Tên"))
        item = self.tb_SinhVien.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày Sinh"))
        item = self.tb_SinhVien.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Giới Tính"))
        item = self.tb_SinhVien.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Địa Chỉ"))
        self.btnAdd.setText(_translate("MainWindow", "Thêm"))
        self.btnUpdate.setText(_translate("MainWindow", "Sửa"))
        self.btnDelete.setText(_translate("MainWindow", "Xóa"))
        self.btnSearch.setText(_translate("MainWindow", "Tìm Kiếm"))
        self.btnThongKe.setText(_translate("MainWindow", "Thống kê"))

    def populate_fields(self, row, column):
        self.txtMaSV.setText(self.tb_SinhVien.item(row, 0).text())
        self.txtHoTen.setText(self.tb_SinhVien.item(row, 1).text())
        self.txtNgaySinh.setText(self.tb_SinhVien.item(row, 2).text())
        self.txtGT.setText(self.tb_SinhVien.item(row, 3).text())
        self.txtDiaChi.setText(self.tb_SinhVien.item(row, 4).text())

    def load_data(self):
        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM SinhVien")
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_idx, row_data in enumerate(rows):
                for col_idx, col_data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_idx, col_idx, QtWidgets.QTableWidgetItem(str(col_data)))

            conn.close()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def add_data(self):
        ma_sv = self.txtMaSV.text()
        ho_ten = self.txtHoTen.text()
        ngay_sinh = self.txtNgaySinh.text()
        gioi_tinh = self.txtGT.text()
        dia_chi = self.txtDiaChi.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO SinhVien (MaSV, HoTen, NgaySinh, GioiTinh, DiaChi) VALUES (?, ?, ?, ?, ?)",
                (ma_sv, ho_ten, ngay_sinh, gioi_tinh, dia_chi)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def update_data(self):
        ma_sv = self.txtMaSV.text()
        ho_ten = self.txtHoTen.text()
        ngay_sinh = self.txtNgaySinh.text()
        gioi_tinh = self.txtGT.text()
        dia_chi = self.txtDiaChi.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE SinhVien SET HoTen = ?, NgaySinh = ?, GioiTinh = ?, DiaChi = ? WHERE MaSV = ?",
                (ho_ten, ngay_sinh, gioi_tinh, dia_chi, ma_sv)
            )
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def delete_data(self):
        ma_sv = self.txtMaSV.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            cursor.execute("DELETE FROM SinhVien WHERE MaSV = ?", (ma_sv,))
            conn.commit()
            conn.close()

            self.load_data()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def search_data(self):
        search_term = self.txtTK.text()

        try:
            conn = pyodbc.connect(connection_string)
            cursor = conn.cursor()
            query = "SELECT MaSV, HoTen, NgaySinh, GioiTinh, DiaChi FROM SinhVien WHERE MaSV LIKE ? OR HoTen LIKE ?"
            cursor.execute(query, ('%' + search_term + '%', '%' + search_term + '%'))
            rows = cursor.fetchall()

            self.tb_SinhVien.setRowCount(len(rows))
            for row_idx, row_data in enumerate(rows):
                for col_idx, col_data in enumerate(row_data):
                    self.tb_SinhVien.setItem(row_idx, col_idx, QtWidgets.QTableWidgetItem(str(col_data)))

            conn.close()
        except pyodbc.Error as e:
            print("Error in connection: ", e)

    def btnThongKe_clicked(self):
        wb = Workbook()
        ws = wb.active
        ws.title = "Danh sách điểm"

        # Ghi tiêu đề cột
        columns = ["Mã SV", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ"]
        for col_idx, col_name in enumerate(columns, 1):
            ws.cell(row=1, column=col_idx, value=col_name)

        # Ghi dữ liệu từ table widget vào worksheet
        for row_idx in range(self.tb_SinhVien.rowCount()):
            for col_idx in range(self.tb_SinhVien.columnCount()):
                item = self.tb_SinhVien.item(row_idx, col_idx)
                ws.cell(row=row_idx + 2, column=col_idx + 1, value=item.text())

        # Đường dẫn lưu file
        directory = "E:\Python"
        if not os.path.exists(directory):
            os.makedirs(directory)
        file_path = os.path.join(directory, "DanhSachSinhVien.xlsx")
        
        # Lưu workbook thành file Excel
        wb.save(file_path)
        QtWidgets.QMessageBox.information(None, "Thông báo", f"File đã được lưu tại {file_path}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_sinhvienWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
