# Form implementation generated from reading ui file 'TrangChu.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from sinhvien import Ui_sinhvienWindow as Ui_sinhvienWindow
from Diem import Ui_DiemWindow as Ui_DiemWindow
from MonHoc import Ui_MonHocWindow as Ui_MonHocWindow
from LopHoc import Ui_LopHocWindow as Ui_LopHocWindow
from DangKyMon import Ui_DangKyMonWindow as Ui_DangKyMonWindow

class Ui_TrangChuWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 348)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSV = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSV.setGeometry(QtCore.QRect(0, 20, 131, 41))
        self.btnSV.setObjectName("btnSV")
        self.btnDKMon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDKMon.setGeometry(QtCore.QRect(0, 80, 131, 41))
        self.btnDKMon.setObjectName("btnDKMon")
        self.btnMonHoc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMonHoc.setGeometry(QtCore.QRect(0, 140, 131, 41))
        self.btnMonHoc.setObjectName("btnMonHoc")
        self.btnLopHoc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLopHoc.setGeometry(QtCore.QRect(0, 200, 131, 41))
        self.btnLopHoc.setObjectName("btnLopHoc")
        self.btnDiem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDiem.setGeometry(QtCore.QRect(0, 260, 131, 41))
        self.btnDiem.setObjectName("btnDiem")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 391, 331))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/VU HONG PHONG/Downloads/dungxoa.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnSV.clicked.connect(self.open_Sinh_Vien_window)
        self.btnDiem.clicked.connect(self.open_Diem_window)
        self.btnDKMon.clicked.connect(self.open_DK_window)
        self.btnLopHoc.clicked.connect(self.open_LH_window)
        self.btnMonHoc.clicked.connect(self.open_MH_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSV.setText(_translate("MainWindow", "Sinh Viên"))
        self.btnDKMon.setText(_translate("MainWindow", "Đăng kí môn"))
        self.btnMonHoc.setText(_translate("MainWindow", "Môn học"))
        self.btnLopHoc.setText(_translate("MainWindow", "Lớp học"))
        self.btnDiem.setText(_translate("MainWindow", "Điểm"))

    def open_Sinh_Vien_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_sinhvienWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_DK_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DangKyMonWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_Diem_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DiemWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def open_LH_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LopHocWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_MH_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MonHocWindow()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TrangChuWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
